# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: interface.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'interface.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finterface.proto\x12\x03its\"\xa0\x01\n\tHeartbeat\x12\x0e\n\x06hb_seq\x18\x01 \x01(\r\x12\x10\n\x08uptime_s\x18\x02 \x01(\r\x12\x11\n\tfree_heap\x18\x03 \x01(\r\x12\x15\n\rmin_free_heap\x18\x04 \x01(\r\x12\x10\n\x08tx_count\x18\x05 \x01(\x03\x12\x10\n\x08rx_count\x18\x06 \x01(\x03\x12\x12\n\nrx_dropped\x18\x07 \x01(\r\x12\x0f\n\x07src_mac\x18\x08 \x01(\x0c\"\x1b\n\x05\x46rame\x12\x12\n\nframe_data\x18\x01 \x01(\x0c\"_\n\rReceivedFrame\x12\x14\n\x0ctimestamp_us\x18\x01 \x01(\x04\x12\x0f\n\x07src_mac\x18\x02 \x01(\x0c\x12\x0c\n\x04rssi\x18\x03 \x01(\x05\x12\x19\n\x05\x66rame\x18\x04 \x01(\x0b\x32\n.its.Frame\"C\n\x07ToBoard\x12\x1b\n\x05\x66rame\x18\x01 \x01(\x0b\x32\n.its.FrameH\x00\x12\x14\n\nrequest_hb\x18\x02 \x01(\x08H\x00\x42\x05\n\x03msg\"e\n\tFromBoard\x12#\n\theartbeat\x18\x01 \x01(\x0b\x32\x0e.its.HeartbeatH\x00\x12,\n\x0ereceived_frame\x18\x02 \x01(\x0b\x32\x12.its.ReceivedFrameH\x00\x42\x05\n\x03msgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interface_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEARTBEAT']._serialized_start=25
  _globals['_HEARTBEAT']._serialized_end=185
  _globals['_FRAME']._serialized_start=187
  _globals['_FRAME']._serialized_end=214
  _globals['_RECEIVEDFRAME']._serialized_start=216
  _globals['_RECEIVEDFRAME']._serialized_end=311
  _globals['_TOBOARD']._serialized_start=313
  _globals['_TOBOARD']._serialized_end=380
  _globals['_FROMBOARD']._serialized_start=382
  _globals['_FROMBOARD']._serialized_end=483
# @@protoc_insertion_point(module_scope)
